### ISSUE TITLE
window width number precision

### ISSUE THREAD

**Issue by broomdodger** [eGust/calc.js#2]
acer c720 chromebook
chromeos 41.0.2272.89
eCalculator v0.6

Thank you. The postfix notation is **great**!

Both infix and postfix, the eCalculator window **wraps** values at 47 characters.
Is it possible to make the window wider to accommodate the max number of characters?
This is what it looks like on this chromebook:

```
50 .7 /
71.4285714285714285714285714285714285714285714

PI 3 * 3 /
3.1415926535897932384626433832795028841971694

PI
3.14159265358979323846264338327950288419716939
93751

E
2.71828182845904523536028747135266249775724709
369996

1 3 /
0.33333333333333333333333333333333333333333333
3
```

**Comment by eGust** [comment]
I knew this problem. Also if you input a long enough int number.

But it's very hard to solve, because users could switch to binary and/or use separators to make the results even longer. So make the window wider is meaningless. 

Or I can make real display only in one line, the overflowed chars are just hidden. But the difference of real and int/string also may make users confused. 

So I won't do it.

**Comment by broomdodger** [comment]
Thank you.
I understand the problem.
eCalculator is still the best calculator I have used on chrome.
